### ISSUE TITLE
MPU-9250 is not a constructor

### ISSUE THREAD

**Issue by rafcichosz** [miniben-90/mpu9250#10]
Dear Miniben,

First of all, thank you for your library. I am trying to integrate MPU-9250 with Beagelbone Black and the library can mean a lot to me.
I downloaded all required dependancies and your example.js.
Unfortunately, I get error in line 40 "mpu9250 is not a constructor"
Any idea why?

Thanks

**Comment by miniben-90** [comment]
Hello,
Can you show me how you are using it ?

Best regard.

**Comment by rafcichosz** [comment]
Hi, thanks for replying
Few words about my application which may be helpful in this matter. I am working on BeagleBone Black. 
Debian 4.4.84 
node v6.11.2
extend 3.0.1
geomagnetism 0.0.2
i2c 0.2.3
sleep 5.1.1.

I am new to i2c bus but it is definitely worthwhile to learn, so I decided to start with MPU-9250 IMU. To begin with I aimed to read raw temp data from 0x41 and 0x42 address using javascript. Few errors later I have found your library which was too difficult to extract just a temp reading, so decided to try it as whole. 
I downloaded your example.js and run it with Putty: `sudo node example.js`
After few sec I got this error:
```
------------------(START SCRIPT)------------------
/home/debian/Sharky/Beta/example.js:40

var mpu = new mpu9250({
          ^
TypeError: mpu9250 is not a constructor
  at Object.<anonymous> (/home/debian/Sharky/Beta/example.js:40:11)
  at Module._compile (module.js:570:32)
  at Object.Module._extensions..js (module.js:579:10)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.runMain (module.js:604:10)
  at run (bootstrap_node.js:389:7)
  at startup (bootstrap_node.js:149:9)
  at bootstrap_node.js:504:3
```

**Comment by miniben-90** [comment]
Hello,
It's normal, you need to download all the project and make npm install on it before using the example file.
Or you can install the library from npm (`npm install mpu9250`), and change the example file :
you need to change `var mpu9250 = require('./mpu9250');` to `var mpu9250 = require('mpu9250');` (ligne 3) and you have to check the device parameter (in the example it's using `/dev/i2c-2`).
I never try on Beagelbone device.

Best regards.
