### ISSUE TITLE
MPU-9255 and WHO_AM_I code (0x73 not 0x71)

### ISSUE THREAD

**Issue by nkolban** [miniben-90/mpu9250#13]
Apparently there is a new MPU-9250 compatible called the MPU-9255 which claims to be compatible.  I recently bought some modules that were listed as MPU-9250 but turned out to be the new MPU-9255.  The puzzle is that the MPU-9255 claims to be device Id 0x73 and not 0x71 (which appears to be the MPU-9250).  Unfortunately, in the implementation of this module, we explicitly look for the deviceId to be 0x71.  When I recoded to 0x73 all seems to work great.  This issues asks for your examination and perhaps a refresh to check that the deviceId is *either* 0x71 or 0x73?

See also:
https://github.com/kriswiner/MPU9250/issues/47

**Comment by miniben-90** [comment]
Hello can you please try with the develop branch and test with your device before I make any merge with e master.
