### ISSUE TITLE
Problems with pre-req of i2c module

### ISSUE THREAD

**Issue by kolban-google** [miniben-90/mpu9250#14]
It seems that one of the dependencies (i2c) is no longer working ... see:

https://github.com/kelly/node-i2c/issues/90

This has the effect of making this package not work.  A suggestion in the threads appears to be to switch to the npm i2c-bus package.

**Comment by rzr** [comment]
Or use this fork:
https://github.com/abandonware/node-i2c

Changes are trivial:
https://github.com/dbridges/bmp085-sensor/pull/9

**Comment by miniben-90** [comment]
I'll check it this Week-End.

**Comment by rzr** [comment]
I think this can be closed now, also I am considering to port this module to iotjs for:
https://github.com/rzr/generic-sensors-lite/issues/10

Is this dependency to sleep strict ? or can we use setTimeout ?
https://github.com/erikdubbelboer/node-sleep

**Comment by miniben-90** [comment]
Yes It's a strict dependency. It's used for waiting times at initialization of the MPU.
