### ISSUE TITLE
never get into mpu.initialize()

### ISSUE THREAD

**Issue by DokRaphael** [miniben-90/mpu9250#7]
I am using the MPU9250 on a rpi zero W, on Raspbian Jessie
node version : v6.10.2
When doing sudo i2cdetect -y 1 , I can see the addresses : 0x0c and 0x68

I have tested the every script and nothing happens. Here is an output example : 

pi@raspberrypi: ~ /nodeMPU/mpu9250 $ sudo node calibrate_accel.js
pi@raspberrypi: ~ /nodeMPU/mpu9250 $

The mpu.initialize() seems to be always false
any idea how to fix this ?

**Comment by miniben-90** [comment]
Hi,
I will try to check next week, I have some trouble with my connection.

**Comment by miniben-90** [comment]
Hello,
Question did you add the debug parameter to see what happened ? Can you give the log ?

**Comment by miniben-90** [comment]
It's working for me, did you try to run node example.js ?

**Comment by DokRaphael** [comment]
Hi
Sorry I did salvage the project, but I will try to put it together again to test it this weekend
I will let you know for the logs
Thanks

**Comment by icebat** [comment]
Seeing the same behavior.
Raspberry pi zero W on Raspbian Jessie Lite.
node v7.9.0
npm 4.2.0
npm install https://github.com/miniben-90/mpu9250

Ran example.js with debug:
[INFO][21:35 20/5/2017]:Initialization MPU9250 ....
[INFO][21:35 20/5/2017]:Reset configuration MPU9250.
[INFO][21:35 20/5/2017]:Enabled magnetometer. Starting initialization ....
[INFO][21:35 20/5/2017]:END of magnetometer initialization.
[INFO][21:35 20/5/2017]:END of MPU9150 initialization.
[INFO][21:35 20/5/2017]:MPU9250:
[INFO][21:35 20/5/2017]:--> Device address: 0x68
[INFO][21:35 20/5/2017]:--> i2c bus: /dev/i2c-1
[INFO][21:35 20/5/2017]:--> Device ID: 0x73
[INFO][21:35 20/5/2017]:--> BYPASS enabled: Yes
[INFO][21:35 20/5/2017]:--> SleepEnabled Mode: Off
[INFO][21:35 20/5/2017]:--> i2c Master Mode: Disabled
[INFO][21:35 20/5/2017]:--> Power Management (0x6B, 0x6C):
[INFO][21:35 20/5/2017]:  --> Clock Source: 1 (Auto selects the best available clock source)
[INFO][21:35 20/5/2017]:  --> Accel enabled (x, y, z): (Yes, Yes, Yes)
[INFO][21:35 20/5/2017]:  --> Gyro enabled (x, y, z): (Yes, Yes, Yes)
[INFO][21:35 20/5/2017]:Accelerometer:
[INFO][21:35 20/5/2017]:--> Full Scale Range (0x1C): ±2g (0)
[INFO][21:35 20/5/2017]:--> Scalar: 1/16384
[INFO][21:35 20/5/2017]:--> Calibration:
[INFO][21:35 20/5/2017]:  --> Offset:
[INFO][21:35 20/5/2017]:    --> x: 0.00943176
[INFO][21:35 20/5/2017]:    --> y: 0.00170817
[INFO][21:35 20/5/2017]:    --> z: 0.05296142
[INFO][21:35 20/5/2017]:  --> Scale:
[INFO][21:35 20/5/2017]:    --> x: -0.993164,1.0102189
[INFO][21:35 20/5/2017]:    --> y: -0.9981974,1.0055884
[INFO][21:35 20/5/2017]:    --> z: -0.9598844,1.0665967
[INFO][21:35 20/5/2017]:Gyroscope:
[INFO][21:35 20/5/2017]:--> Full Scale Range (0x1B): +250dps (0)
[INFO][21:35 20/5/2017]:--> Scalar: 1/131
[INFO][21:35 20/5/2017]:--> Bias Offset:
[INFO][21:35 20/5/2017]:  --> x: -1.068045801
[INFO][21:35 20/5/2017]:  --> y: -0.156656488
[INFO][21:35 20/5/2017]:  --> z: 1.3846259541
[INFO][21:35 20/5/2017]:Magnetometer (Compass):
[INFO][21:35 20/5/2017]:--> i2c address: 0xc
[INFO][21:35 20/5/2017]:--> Device ID: 0x48
[INFO][21:35 20/5/2017]:--> Mode: 0x06 (Continuous measurement mode 2: 100Hz)
[INFO][21:35 20/5/2017]:--> Scalars:
[INFO][21:35 20/5/2017]:  --> x: 1.21875
[INFO][21:35 20/5/2017]:  --> y: 1.21875
[INFO][21:35 20/5/2017]:  --> z: 1.171875

Changed mpu9250.js
 line 280
 return this.testDevice();
 to
 return true;

mpu.initialize() returns true now and example.js runs as expected.
