### ISSUE TITLE
getYaw always returns 0

### ISSUE THREAD

**Issue by icebat** [miniben-90/mpu9250#8]
getPitch and getRoll return a value
getYaw always returns 0

I noticed in mpu9250.js:
line 575 mpu9250.prototype.getYaw = function(value) {
line 576	return 0;

is there another way to get yaw or heading?

**Comment by miniben-90** [comment]
If I remember correctly you have to calculate it

**Comment by Guttata** [comment]
Hi,
Does someone implement it ?

Thanks a lot.
